FROM richarvey/nginx-php-fpm:latest
MAINTAINER  Ake Zakrified <ake.zakky@gmail.com>

ADD wordpress.conf /etc/nginx/sites-enabled/wordpress.conf
#ADD wordpressreload.sh /wordpressreload.sh
CMD ["/start.sh"]

